# Generated by Django 3.0.6 on 2020-06-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('png_path', models.CharField(max_length=258)),
                ('wav_path', models.CharField(max_length=258)),
                ('json_path', models.CharField(max_length=258)),
                ('score_name', models.CharField(max_length=258)),
            ],
        ),
    ]
