# Generated by Django 3.0.6 on 2020-06-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp_login', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
    ]
